### Create embedding for dummy data 

In [13]:
import torch
from src.data_prep.transcode import Tokenizer #get simple encoder for demonstration

In [14]:
s="She sells seashells by the seashore, The shells she sells are surely seashells, So if she sells shells on the seashore, I'm sure she sells seashore shells."

In [16]:
# encode the text
tk=Tokenizer()
enc,dec=tk.transcode(s)
encoded_text=tk.encode(s,enc)
print(encoded_text)


[4, 14, 12, 8, 19, 13, 1, 6, 16, 15, 14, 7, 18, 12, 1, 5, 9, 15, 14, 16, 11, 19, 13, 1, 3, 0, 10, 17, 15, 14, 13, 16, 2]


In [24]:
# convert text into torch tensor
tt=torch.tensor(encoded_text)
print(tt)
print('length of tt:',len(tt))

tensor([ 4, 14, 12,  8, 19, 13,  1,  6, 16, 15, 14,  7, 18, 12,  1,  5,  9, 15,
        14, 16, 11, 19, 13,  1,  3,  0, 10, 17, 15, 14, 13, 16,  2])
length of tt: 33


In [25]:
# create an embedding layer with desired vocabulary size and number of dimensions required for each word in vocab
vocab_size=50
dimensions=5
torch.manual_seed(43)
embed=torch.nn.Embedding(vocab_size,dimensions)
print(embed.weight)

Parameter containing:
tensor([[-0.0166, -0.4668,  2.0909,  0.6149, -0.5621],
        [-0.4143, -1.3001, -0.1012, -1.0999, -0.4687],
        [-0.8400,  0.6868, -0.0678, -0.0886, -0.3124],
        [-0.3552,  0.7142,  0.4198, -1.7672, -0.4996],
        [ 0.3083, -0.2947, -0.7662, -0.9962,  0.7781],
        [-0.6856, -0.7326,  0.3004, -0.3630,  1.5822],
        [-0.4430,  1.8462, -0.7115,  1.0425, -0.7618],
        [-0.4830, -0.7771, -0.4484, -1.1668,  0.5006],
        [ 1.3251, -1.1627, -2.1186,  0.5470, -1.1668],
        [-1.0199,  1.6283,  0.3475, -0.1191, -1.5415],
        [ 0.6421,  1.5016, -0.1955,  0.7438,  1.3611],
        [ 0.7930,  0.4777,  0.9248,  0.8841,  0.7809],
        [ 0.4664, -2.2619,  0.5374, -0.8002,  1.6715],
        [-0.3596, -2.1513, -1.3592, -0.7203, -0.5679],
        [-0.5438,  1.8492, -0.0085, -0.4166,  0.4745],
        [-0.4395, -0.7560,  1.1363,  1.2756,  0.1642],
        [ 2.7160,  0.8090, -1.0697, -0.1990, -0.9886],
        [-2.1535,  0.3912,  1.5218, -0.5329

In [26]:
#create embeded text map by mapping encoded tensor to the created embeded layer
#The current embedding layer only contains random weights but this can be trained with the actual text to assign text semantic meaning
embeded_text=(embed(tt))
print(embeded_text)

tensor([[ 0.3083, -0.2947, -0.7662, -0.9962,  0.7781],
        [-0.5438,  1.8492, -0.0085, -0.4166,  0.4745],
        [ 0.4664, -2.2619,  0.5374, -0.8002,  1.6715],
        [ 1.3251, -1.1627, -2.1186,  0.5470, -1.1668],
        [-0.4446, -1.2036, -0.8498, -0.1835, -0.7464],
        [-0.3596, -2.1513, -1.3592, -0.7203, -0.5679],
        [-0.4143, -1.3001, -0.1012, -1.0999, -0.4687],
        [-0.4430,  1.8462, -0.7115,  1.0425, -0.7618],
        [ 2.7160,  0.8090, -1.0697, -0.1990, -0.9886],
        [-0.4395, -0.7560,  1.1363,  1.2756,  0.1642],
        [-0.5438,  1.8492, -0.0085, -0.4166,  0.4745],
        [-0.4830, -0.7771, -0.4484, -1.1668,  0.5006],
        [-0.2966, -0.3325, -0.4449, -0.1949, -0.0895],
        [ 0.4664, -2.2619,  0.5374, -0.8002,  1.6715],
        [-0.4143, -1.3001, -0.1012, -1.0999, -0.4687],
        [-0.6856, -0.7326,  0.3004, -0.3630,  1.5822],
        [-1.0199,  1.6283,  0.3475, -0.1191, -1.5415],
        [-0.4395, -0.7560,  1.1363,  1.2756,  0.1642],
        [-